# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[83, 18],
       [68, 74],
       [82,  0],
       [19, 67],
       [81, 55],
       [35, 72],
       [82, 81],
       [82, 69],
       [83,  5],
       [34, 52]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

/home/carbon/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[1.        , 0.22222222],
       [0.765625  , 0.91358025],
       [0.984375  , 0.        ],
       [0.        , 0.82716049],
       [0.96875   , 0.67901235],
       [0.25      , 0.88888889],
       [0.984375  , 1.        ],
       [0.984375  , 0.85185185],
       [1.        , 0.0617284 ],
       [0.234375  , 0.64197531]])

In [8]:
# In one step
result = scaler_model.fit_transform(data)

/home/carbon/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
result

array([[1.        , 0.22222222],
       [0.765625  , 0.91358025],
       [0.984375  , 0.        ],
       [0.        , 0.82716049],
       [0.96875   , 0.67901235],
       [0.25      , 0.88888889],
       [0.984375  , 1.        ],
       [0.984375  , 0.85185185],
       [1.        , 0.0617284 ],
       [0.234375  , 0.64197531]])

In [10]:
import pandas as pd

In [11]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [12]:
data.head()

f1  f2  f3  label
0  100   2  55     83
1    0  56  17     29
2   98  70  49     50
3  100  72  27     73
4   98  95  93     39

In [13]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [16]:
X_train.shape

(35, 3)

In [17]:
X_test.shape

(15, 3)

In [18]:
y_train.shape

(35,)

In [19]:
y_test.shape

(15,)

## Great Job!